### ISSUE TITLE
Decoding of "-" not working

### ISSUE THREAD

**Issue by ezrarieben** [kminek/email-obfuscator#1]
If the domain of an email adress contains a `-` it won't decode the character correctly in JS.

Entered Value: `\Kminek\EmailObfuscator::obfuscate('foobar@some-domain.com')`

Value after JS decoding: `foobar@someZdomain.com` sometimes `foobar@someHdomain.com`

**Comment by kminek** [comment]
hello @ezrarieben thx for reporting - the issue has been fixed :)
