### ISSUE TITLE
Obfuscate only mode

### ISSUE THREAD

**Issue by shadowlmd** [kminek/email-obfuscator#2]
Hi!

Thanks for packaging this one!

I'd like to request a feature: an option to only obfuscate email, without converting it to a mailto link, like Cloudflare does. Would be really nice. :)

**Comment by kminek** [comment]
@shadowlmd so you want it to print just the email without the surrounding `<a></a>` mailto link right? :)

**Comment by shadowlmd** [comment]
@kminek, exactly. :)

**Comment by kminek** [comment]
this is now possible using following syntax: `obfuscate_email('sample@domain.com', null, ['mailto' => false])`
