### ISSUE TITLE
Problem with some characters

### ISSUE THREAD

**Issue by shadowlmd** [kminek/email-obfuscator#3]
There is an issue with obfuscation emails containing, for example, underscore characters. `domain-contact_ww_grp@oracle.com` becomes `domain-contactYwwYgrp@oracle.com`.

**Comment by shadowlmd** [comment]
The root cause is probably the same as in #1. Here's the regexp that represents valid emails: `/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i`. I suggest at least the following characters should be added to `$unmixedkey`: `_%+`.

**Comment by kminek** [comment]
@shadowlmd fixed, thanks for reporting!
